### ISSUE TITLE
Compatibility with Prop-types

### ISSUE THREAD

**Issue by sreetamdas** [nickstanish/reprogressbars#9]
As `prop-types` is no longer shipped with React, the code needs to be updated, since the following error is shown at the moment:

![image](https://user-images.githubusercontent.com/11270438/37388559-0a2dddac-2787-11e8-90ef-4aa5a800f263.png)

**Comment by nickstanish** [comment]
@sreetamdas What version are you using? I believe this was fixed in v1.0.0
